### ISSUE TITLE
Missing some components while deploying..

### ISSUE THREAD

**Issue by amispn123** [logontokartik/VFDynamicComponents#1]
Failures:
objects/Component__c.object(Component__c):componenteditnew does not exist or is not a valid override for action Edit.
components/VFDataTable.component(VFDataTable):Apex class 'DatatableCon' does not exist
pages/SampleDataTable.page(SampleDataTable):Apex class 'DatatableCon' does not exist
pages/ContactListViaRemoteObjects.page(ContactListViaRemoteObjects):Invalid field 'Contact.Image_URL__c' specified. Ensure that you use the full API name for any custom fields.
pages/ComponentEditNew.page(ComponentEditNew):Apex class 'ComponentEditNewCon' does not exist
classes/DatatableCon.cls(1,35):Invalid type: ComponentBase
classes/ComponentEditNewCon.cls(12,9):Invalid type: ComponentRegistration__c
Status: Completed 
Deployment Complete
Failures:
objects/Component__c.object(Component__c):componenteditnew does not exist or is not a valid override for action Edit.
components/VFDataTable.component(VFDataTable):Apex class 'DatatableCon' does not exist
pages/SampleDataTable.page(SampleDataTable):Apex class 'DatatableCon' does not exist
pages/ContactListViaRemoteObjects.page(ContactListViaRemoteObjects):Invalid field 'Contact.Image_URL__c' specified. Ensure that you use the full API name for any custom fields.
pages/ComponentEditNew.page(ComponentEditNew):Apex class 'ComponentEditNewCon' does not exist
classes/DatatableCon.cls(1,35):Invalid type: ComponentBase
classes/ComponentEditNewCon.cls(12,9):Invalid type: ComponentRegistration__c

**Comment by logontokartik** [comment]
Will add them, sorry abt that I am still working on loading them to github :)

**Comment by logontokartik** [comment]
You should all be set now. Please use the Deploy to Salesforce Button in Readme to easily deploy in your org.
